on:
  push:
    branches:
      - main
      - master

name: Build

jobs:
  Build_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-pandoc@v3

      - name: Install dependencies
        run: make install

      - name: build html
        run: make
        
      - name: build pdf
        run: make pdf

      - name: prepare deployment
        run: |
          mkdir docs
          mv index.html docs/
          if [ -d index_files ]; then
            mv index_files docs/
          fi
          mv assets docs/
          mv conf docs/
          mv images docs/
          mv slides.pdf docs/
      
      - name: Deploy gh_pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: docs
          SINGLE_COMMIT: true
